### PR TITLE
add makefile based on legacy r3px userspace drivers

### PR DESCRIPTION
**Pull request by giuliobenetti**

### CODE REVIEW

**Comment by giuliobenetti** [comment]
I've noticed right now that I've mixed sunxi-mali and sunxi-mali-proprietary with your repo.
Is it ok this way, or do I have to modify sunxi-mali-proprietary adding you subgit?

**Comment by tpetazzoni** [comment]
This is doing a lot more than adding a Makefile. It's moving a lot of files around. Please split in more fine grained commits.

**Comment by tpetazzoni** [comment]
I don't understand your comment about sunxi-mali vs sunxi-mali-proprietary.

**Comment by giuliobenetti** [comment]
Ok for splitting in more commits

**Comment by giuliobenetti** [comment]
For sunxi-mali vs sunxi-mali-proprietary I mean that sunxi-mali uses a submodule containing the effective library(sunxi-mali-proprietary).
Instead I've mixed things up.

**Comment by tpetazzoni** [comment]
I think @mripard's logic with this ```mali-blobs``` repository is to provide something that one can drop in the ```lib/mali``` subfolder of ```sunxi-mali```, to add the r6p2 binary blobs. Indeed, Maxime's blog post at http://free-electrons.com/blog/mali-opengl-support-on-allwinner-platforms-with-mainline-linux/ doesn't mention where the OpenGL headers and al. would be coming from.

@mripard could you comment/clarify ?

**Comment by giuliobenetti** [comment]
I could add a git submodule pointing to https://github.com/free-electrons/mali-blobs under lib,
and modify the "sunxi-mali" base Makefile to work differently if compiling r6p2.
So I could leave this Repo untouched.
What do you think?

**Comment by tpetazzoni** [comment]
And this would be contributed to the ```linux-sunxi/sunxi-mali``` Github project instead ?

**Comment by giuliobenetti** [comment]
Yes, maybe this could be a clean way, what do you think?

**Comment by tpetazzoni** [comment]
Let's see what @mripard thinks about it.

**Comment by giuliobenetti** [comment]
I've seen linux-sunxi/sunxi-mali seems dead.
Only https://github.com/retr0rangepi/sunxi-mali went on until r4p0.
Could it be ok if I fork and we keep my github url?
This way I could delete completely the legacy libs,
because they don't fit with new buildroot package sunxi-mali-mainline

**Comment by mripard** [comment]
I've never really thought about this, but I don't really see either why we'd need a Makefile to replace a single cp?

linux-sunxi is indeed pretty much dead, so I wouldn't rely too much on it.

**Comment by giuliobenetti** [comment]
I think like you about libs and headers.
But malitest and maliver seems to be still useful.
Even if they’re purely to debug.
What do you think?

Inviato da iPhone

**Comment by giuliobenetti** [comment]
It’s also true that this user space blob will be matched with mainline driver package on buildroot that I’m releasing.
Maybe let’s go with only cp in package.
Easier and cleaner.

Alright?

**Comment by giuliobenetti** [comment]
Worked around with a buildroot package that as @mripard  says just copies headers and libraries from this repository.
We can consider this closed to me.

**Pull request closed without merging**
